### ISSUE TITLE
Is there a list of Post-Mortems somewhere?

### ISSUE THREAD

**Issue by daviddias** [protocol/infra-team#18]
ref https://github.com/protocol/infra-team#post-mortems-skull

**Comment by eefahy** [comment]
We have held exactly one post mortem that I have notes for but I need to convert to markdown and post here. Hence the note that they _will be_ posted in this repo. I made issue https://github.com/protocol/infra-team/issues/23 to track that work.

**Comment by daviddias** [comment]
@eefahy I believe there are post-mortems from 2015, 2016 and 2017 too //cc @lgierth
