### ISSUE TITLE
Scaleway account

### ISSUE THREAD

**Issue by Kubuxu** [protocol/infra-team#27]
Would it be possible to create corporate Scaleway account?

They provide cheap, small and **baremetal** instances which I am considering using for network benchmarking.

**Comment by mburns** [comment]
Could you be persuaded to use [Packet](https://www.packet.com/) as a baremetal provider. That is where we are doing the rust-proofs benchmarking (as well as running the IPFS gateways)?

**Comment by Kubuxu** [comment]
The cheapest on packet.net is $0.4/h. I don't have anything against using it but running 10 or 20 of these for hours at a time will get pricey pretty quickly.

**Comment by Kubuxu** [comment]
For comparison this is offering of Scaleway when it comes to dedicated servers:
![scaleway](https://user-images.githubusercontent.com/2259282/52362580-36138300-2a41-11e9-8e9e-ba36300a53a6.png)

**Comment by mburns** [comment]
Fair point. Those are certainly cheaper.

We're thankfully on the verge of turning off some of our hosting providers, so standing up Scaleway should't be hard. Will work with @scout on the particulars.

**Comment by Kubuxu** [comment]
They are not powerful or fast servers but they do just fine as a stable reference.

**Comment by scout** [comment]
FYI Packet has a “tiny” bare metal for $0.07/hr - still a little more expensive then Scaleway but we would be able to reuse tf stuff. Would this do? https://www.packet.com/cloud/servers/t1-small/

**Comment by Kubuxu** [comment]
The question is whether it is physical reserved cores/RAM banks or the same situation as with AWS with a possibility of getting a noisy neighbour. It seems like it is still fully isolated.
 
Looks like it will do the job. If it doesn't I will reopen this request.
