### ISSUE TITLE
infra-team/README.md contains invalid (404) links

### ISSUE THREAD

**Issue by r0h4n** [protocol/infra-team#40]
I am new to learning ipfs and other interesting tech from protocol.ai.  While reading the README.md I found a few links with text "protocol/infra" which point to "https://github.com/protocol/infra" which doesnt exist.

I guess the correct location would be "https://github.com/protocol/infra-team"

Thanks.

**Comment by r0h4n** [comment]
"https://github.com/protocol/infra" may be a private repo and hence I am not able to access it. Please close the issue if that is the case

**Comment by mburns** [comment]
Hi @r0h4n 

You guessed it, `protocol/infra` is a private repo (and largely being deprecated as we refactor various projects).

Reading the REAME, it isn't super obvious. In particular, we should rephrase the bullet point under [Urgent Requests](https://github.com/protocol/infra-team#urgent-requests--outage-reporting-rotating_light):

>Make an issue in protocol/infra and label the issue with firefighting and P0 - Critical

@scout thoughts?

**Comment by scout** [comment]
@mburns Marking it as a private repo makes sense to clear up confusion. I'll post a PR for that today.

Also, welcome @r0h4n to the community. Please let us know if we can tidy up our README's or post answers to any questions that you have.
